### ISSUE TITLE
Allow multiple directory configuration

### ISSUE THREAD

**Issue by prolic** [malukenho/docheader#1]
I see two different options:

1) allow even more params, f.e.

```
./vendor/bin/docheader check examples src tests
```

2) add another config file, f.e.

.docheader - contains a list directories and files to check
.docheaderlicense - contains the sample license

**Comment by malukenho** [comment]
@prolic I'll go with the first approach. Two config files seems to be overkill for me (at least for now).

**Comment by prolic** [comment]
nice, thanks.

**Comment by malukenho** [comment]
Handled in #2
New version `0.1.3` was released
