### ISSUE TITLE
Feature request: --exclude flag

### ISSUE THREAD

**Issue by weierophinney** [malukenho/docheader#13]
We often have test assets such as test configuration files that do not and should not have license docblocks. However, because they are PHP files, they are scanned and docheader correctly points out that they are missing license headers.

As such, I request an `--exclude` flag for the binary, and/or an `--exclude-dir` flag. The flag(s) should allow multiple invocations:

```bash
# Multiple --exclude flags:
$ docheader check test --exclude test/TestAsset/config.php --exclude test/Foo/TestAsset/config.php
# Multiple --exclude-dir flags:
$ docheader check src test --exclude-dir test/TestAsset --exclude-dir test/Foo/TestAsset
```

Any items matching the flag(s) would then be excluded when performing checks.

**Comment by malukenho** [comment]
Handled on #14
