### ISSUE TITLE
Feature request: Add configuration block to .docheader

### ISSUE THREAD

**Issue by antoine-pous** [malukenho/docheader#16]
This package is incredibly usefull, but we can't use configuration from file.

Using another block into .docheader would be awesome :)

```
/*
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This software consists of voluntary contributions made by many individuals
 * and is licensed under the MIT license.
 */
// ==DocHeader==
// @include *.php *.js style.css
// @exclude vendor/ *.md hello.jpg
// @path public/css/ public/js/ app/
// ==/DocHeader==
```

Features:

**@include** List of included filenames/extensions, other files are ignored
**@exclude** List of excluded directories/filenames/extensions, these directories and files are ignored 
**@path** List of included paths, other directories are ignored

Using .docheader is the most common way to manage this feature, we don't really need .docheaderconfig or any another file.

**Comment by malukenho** [comment]
I don't think it's a good ideia. Mixing the `.docheader` template file with configurations would be bad in some points.

* Changes on config doesn't need to affect the template. It'd polute the git history unnecessarily
* There'd be no way to identifier an specific `.docheader`
* Bring to it unneeded complexity
* Configurations can be done via `composer.json` file  as cli parameters (`scripts` section?)

But I'd love to hear what @weierophinney and @Ocramius think about that...

**Comment by Ocramius** [comment]
Mixing is indeed not a good idea. Would rather have `.docheader` and `.docheader.config.php` or such
