### ISSUE TITLE
Feature request: Support documentation tags

### ISSUE THREAD

**Issue by antoine-pous** [malukenho/docheader#18]
Currently docheader check if the header is strongly identical to the `.docheader` content.

But this is not really usefull, because we regulary need to add some @tags for the documentation.

Can you support the documentation tags?

```
/*
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This software consists of voluntary contributions made by many individuals
 * and is licensed under the MIT license.
 *
 * @category
 * @package
 * @license
 * @author
 */
```

Manage optional tags like this `@tag|` would be really usefull :+1:

**Comment by malukenho** [comment]
@antoine-pous It can't be made by using regex?

**Comment by antoine-pous** [comment]
Provide an helper is, for me, the better way to do it and will simplify the use of docheader in most of projects.

More use is simple and intuitive, more docheader will impose itself in projects :)

**Comment by malukenho** [comment]
@antoine-pous the problem that I see is that license should not change over files on the same project. What you're putting in there as `tags` seems more like `docblocks`.

However, you can just check against

```
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This software consists of voluntary contributions made by many individuals
 * and is licensed under the MIT license.
```

If you think it still valid, please, let me know. But keep in mind that, It's about licensing stuff, not documentation ok?

**Comment by antoine-pous** [comment]
But you named your package docheader, not licenseheader.

This name implies that the header documentation is supported

**Comment by malukenho** [comment]
The fact is that documentation change from file to file, a doc/license header should be consistent between all files. Sorry if you got confused by that. I'll try to improve documentation in that sense.
