### ISSUE TITLE
No details when there is an error

### ISSUE THREAD

**Issue by bernard-ng** [malukenho/docheader#23]
I followed the instructions in the documentation and executing the command I had as a message **"something went wrong"**
there are no details, how could I know where things have gone wrong or what is wrong?

**Comment by malukenho** [comment]
Hello @bernard-ng!
The **"Something went wrong!"** phrase should be displayed after a list of file names and path where it wasn't possible to find a matching on the content against the `.docheader` file.

May you provide a test case for your scenario as I couldn't reproduce it locally?

**Comment by bernard-ng** [comment]
oh, i thought i had to complete the ```.docheader``` file and the tool go add the content of the ```.docheader``` in all files that are in the chosen directory

**Comment by malukenho** [comment]
No problem, I'll try to improve the `README` to avoid this problem in the future.
