### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by DannyvdSluijs** [malukenho/docheader#3]
Would it be an option to have a stable release (V1.0.0.) to eliminate the fact that the composer.json would need a minimum-stability: "dev" as this is unwanted for some production application we are having at our company. 

But I do like to have an automated check for the correct headers.

+1 for this package.

**Comment by malukenho** [comment]
@DannyvdSluijs you can use `^0.1.3` version for now without have to set the `minimum-stability` to `dev`
