### ISSUE TITLE
Regex patterns

### ISSUE THREAD

**Issue by weierophinney** [malukenho/docheader#5]
It'd be quite useful to be able to specify placeholders and regex patterns to run.

As an example, in the copyright block, the begin date should be the first year when the specific file was created, not the project. So, it'd be useful to be able to have something  like the following in the `.docheader`:

```
* @copyright Copyright (c) %re:^20\d{2}$%-%year% Foo Bar. (https://example.com/foo/bar)
```

I've arbitrarily chose the spec `%re:PATTERN%`, but I'd be open to other ideas as well. The main thing is that, when encountered, it'd try and match that pattern in order to validate it.

**Comment by malukenho** [comment]
Thanks @weierophinney.
It's possible to use regex using `%regexp:PATTERN%` on `.docheader` file since `0.1.5` version

**Comment by weierophinney** [comment]
I started with the following, which has always worked:

``` php
/**
 * @see       https://github.com/zendframework/zend-expressive for the canonical source repository
 * @copyright Copyright (c) 2015-%year% Zend Technologies USA Inc. (http://www.zend.com)
 * @license   https://github.com/zendframework/zend-expressive/blob/master/LICENSE.md New BSD License
 */
```

I then tried replacing `2015` with each of the following:
- `%regexp:20\d{2}%`
- `20%regexp:\d{2}%`
- `20%regexp:\d\d%`
- `20%regexp:\\d\\d%`
- `20%regexp:[0-9][0-9]%`

None of these worked; every file was flagged. In looking at how the `RegExp` class works, I had a suspicion that perhaps it was being greedy when looking for the closing `%` tag, and tried using this date range instead, to see if that were the issue:
- `2015-%regexp:20\d{2}%`

That still didn't work, so I tried each of the variants from above as well, in substitution for the `%year%` placeholder.

Feel free to use the above for test cases; I'd love to figure this out, and can test patches if you ping me.

**Comment by malukenho** [comment]
@weierophinney re-tagged `0.1.5` with this fixes
